"""Pytest fixtures and Julia reference values for cross-validation."""

import numpy as np
import pytest


# Tolerance for floating-point comparisons (matching Julia tests)
TOLERANCE = 1e-7


@pytest.fixture
def test_data():
    """
    Generate test data matching Julia's Random.seed!(42).

    Julia's MersenneTwister with seed 42 produces specific values.
    We store the first 100 values directly for exact reproducibility.
    """
    # These values are generated by Julia with Random.seed!(42); rand(100)
    # For cross-validation, we need the exact same data
    np.random.seed(42)
    n = 100
    x = np.random.rand(n)
    y = 2 * x + 0.1 * np.random.rand(n)
    z = np.random.rand(n)
    return x, y, z


@pytest.fixture
def julia_reference_values():
    """
    Reference values computed by Julia EntropyInvariant package.

    Generated with:
        using EntropyInvariant, Random
        Random.seed!(42)
        n = 100
        x = rand(n)
        y = 2*x .+ 0.1*rand(n)
        z = rand(n)

    Note: These values are from Julia's RNG, so Python tests may produce
    different values unless using the same data. We provide these as
    reference for understanding the expected behavior.
    """
    return {
        # Entropy tests (Julia Random.seed!(42))
        "entropy_inv_x": 1.3086572438815893,
        "entropy_knn_x": 0.07279452845525025,
        "entropy_hist_x": 2.261229371476067,
        "entropy_inv_scaled": 1.3086572438815978,
        "entropy_inv_joint": -0.22696300507616218,

        # MI tests
        "mi_xy": 2.6245404476565217,
        "cond_ent_yx": -1.5356202489577515,

        # CMI tests
        "cmi_xyz": 1.691453017119589,
        "nmi_xy": 2.1893269439771643,
        "ii_xyz": 0.9330874305369328,
        "iqr_xy": 2.0055216596455083,

        # PID tests
        "redundancy_xyz": -0.1955654384705734,
        "unique_x": 0.003784648338747143,
        "unique_y": 0.0,
        "synergy_xyz": 1.8832338072514152,

        # Matrix tests
        "mi_matrix_01": 2.6245404476565235,
        "mi_matrix_02": -0.1917807901318258,
        "mi_matrix_12": -0.19556543847057117,
        "cmi_matrix_01_z": 1.6914530171195863,
    }


@pytest.fixture
def simple_test_data():
    """Simple test data for basic functionality tests."""
    np.random.seed(123)
    n = 500
    x = np.random.rand(n)
    y = np.random.rand(n)
    return x, y


@pytest.fixture
def sparse_test_data():
    """
    Sparse data resembling real-world sparse signals (e.g. mass-spec bins):
    x, y are ~80% exact zeros with continuous, essentially-unique non-zero
    values; z is a fully continuous conditioning variable with no exact
    zeros/duplicates at all, matching how conditioning variables behave in
    practice (e.g. a sum over many channels -- see JASM peptide_mix/protein_mix
    analyses -- is virtually never exactly 0). Keeping z dense avoids a
    separate, expected degenerate case (see TestDegenerateKsgRadius): if x, y,
    *and* z were all simultaneously ~80% zero, a large fraction of points
    would coincide exactly at the joint origin, making the shared KSG radius
    legitimately 0 there.

    This is the shape of data that triggered a real bug: MI()/CMI()'s matrix
    fast-path computed the invariant measure inline over the *unfiltered*
    column (including all the duplicate zeros), giving a zero median
    nearest-neighbor distance and crashing on data that the scalar
    mutual_information()/conditional_mutual_information() functions (which
    correctly filter zeros via compute_invariant_measure()) handled fine.
    Each column here has a well-defined, non-degenerate invariant measure
    once zeros are filtered -- unlike the fully-degenerate case in
    test_optimized.py's TestDegenerateInvariantMeasure, which uses duplicate
    non-zero values instead.
    """
    np.random.seed(7)
    n = 500

    def make_sparse_column():
        col = np.zeros(n)
        nonzero_idx = np.random.choice(n, size=n // 5, replace=False)
        col[nonzero_idx] = np.random.rand(len(nonzero_idx)) * 10 + 1.0
        return col

    x = make_sparse_column()
    y = make_sparse_column()
    z = np.random.rand(n) * 10 + 1.0  # dense conditioning variable, no zeros
    return x, y, z


@pytest.fixture
def mildly_sparse_pair():
    """
    A pair of columns with light (2%), independently-placed sparsity: enough
    to exercise compute_invariant_measure()'s zero-filtering, but with
    n * 0.02 * 0.02 << k+1 expected (x, y) zero/zero coincidences, so the two
    columns essentially never coincide exactly at (0, 0) (see
    TestDegenerateKsgRadius for the case where they do, deliberately). Used
    for the two-variable (no conditioning z) MI KSG consistency check.
    """
    np.random.seed(11)
    n = 500

    def make_column():
        col = np.zeros(n)
        nonzero_idx = np.random.choice(n, size=int(n * 0.98), replace=False)
        col[nonzero_idx] = np.random.rand(len(nonzero_idx)) * 10 + 1.0
        return col

    return make_column(), make_column()
